#ifndef RCC_REGISTERS_H
#define RCC_REGISTERS_H

// Address for AHB1 clock
#define RCC_AHB1_BUS 0x40020000

// OFFSETS FOR RCC REGISTER
#define RCC_RCC (0x00003800 + RCC_AHB1_BUS)

// OFFSETS FOR RCC
#define RCC_RCC_CONTROL_AHB1_PERPH_RESET      (0x10 + RCC_RCC)
#define RCC_RCC_CONTROL_AHB1_ENABLE           (0x30 + RCC_RCC)
#define RCC_RCC_CONTROL_AHB1_LOW_POWER_ENABLE (0x30 + RCC_RCC)
#define RCC_RCC_CONTROL_CLOCK                 (0x00 + RCC_RCC)
#define RCC_RCC_CONTROL_APB1_ENABLE           (0x40 + RCC_RCC)
#define RCC_RCC_CONTROL_APB2_ENABLE           (0x44 + RCC_RCC)
#define RCC_RCC_CONTROL_PLL_CONFIG            (0x04 + RCC_RCC)
#define RCC_RCC_CONTROL_CLOCK_CONFIG          (0x08 + RCC_RCC)

// POWER
#define RCC_POWER_VOLT_REG (0x40007000)

#endif